### ISSUE TITLE
Initial Climate Data Model standard (subset)

### ISSUE THREAD

**Issue by isedwards** [opencdms-dev/pyopencdms-old#73]
This epic captures the timeframe to the initial version of the WMO Climate Data Model (CDM) storage standard being available.

Due to the majority of this work occurring outside of the OpenCDMS project, this epic may only contain a single issue (to create SQLAlchemy models for CDM) - however, the epic will also be a dependency required by other issues.

Or multiple issues, undertaken in OpenCDMS RI
- [ ] Station
- [ ] Subset of metadata

**Approach TBD**
- Toolchain to create SQL DDL, then we inspect with automated tools to make Python object models
- Write models directly in Python (requires knowledge of SQLAlchemy)

**Comment by david-i-berry** [comment]
Test data required

- [ ] observations, long time period (30 years+) for one station
- [ ] observations, one month for multiple stations in region
- [ ] discovery metadata
- [ ] station metadata for those included in observations (from OSCAR Surface)
- [ ] provenance metadata
